services:
  certbot-service:
    image: certbot-service
    build:
      context: .
    env_file:
      - .env
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    depends_on:
      minio:
        condition: service_healthy
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address :9001
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      timeout: 5s
      retries: 1
  minio-init:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 minioadmin minioadmin;
        (mc ls local/test || mc mb local/test);
      "
    depends_on:
      minio:
        condition: service_healthy
