app = 'postgres-new-proxy'

primary_region = 'iad'

[env]
DEBUG = 'proxy*'

[[services]]
internal_port = 5432
protocol = "tcp"
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1

[[services.ports]]
port = 5432

[services.concurrency]
type = "connections"
soft_limit = 2000
hard_limit = 2500

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
