app = 'postgres-new-proxy'

primary_region = 'iad'

[build]
dockerfile = "Dockerfile"
ignorefile = ".dockerignore"

[[services]]
internal_port = 5432
protocol = "tcp"
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 5432

[services.concurrency]
type = "connections"
soft_limit = 20
hard_limit = 25

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
