name: Run Migrations

on:
  push:
    branches:
      - main

jobs:
  run-migrations:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PROD_DB_PASSWORD }}
      PROJECT_ID: ${{ vars.SUPABASE_PROD_PROJECT_ID }}

      # Create placeholder vars so that supabase/config.toml can load
      SUPABASE_AUTH_GITHUB_CLIENT_ID: placeholder
      SUPABASE_AUTH_GITHUB_SECRET: placeholder
      SUPABASE_AUTH_GITHUB_REDIRECT_URI: placeholder

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
